module.exports = {
  repo10: [
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
  ],
  repo20: [
    ['.current.json', 1, 1, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/.gitignore', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/README.md', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/start/Makefile', 1, 1, 1],
    ['basics-course/start/README.md', 1, 1, 1],
  ],
  repo30: [
    ['.current.json', 1, 1, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/.gitignore', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/README.md', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/start/Makefile', 1, 1, 1],
    ['basics-course/start/README.md', 1, 1, 1],
  ],
  repo30changed: [
    ['.current.json', 1, 0, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 0],
    ['README.md', 1, 1, 1],
    ['basics-course/example/.gitignore', 1, 0, 1],
    ['basics-course/example/Makefile', 1, 2, 0],
    ['basics-course/example/README.md', 1, 0, 1],
    ['basics-course/example/file1', 1, 2, 1],
    ['basics-course/example/file3', 0, 2, 0],
    ['basics-course/example/file6', 0, 0, 3],
    ['basics-course/example/subdir/file2', 1, 2, 2],
    ['basics-course/example/subdir/file4', 0, 2, 2],
    ['basics-course/example/subdir/file5', 0, 2, 3],
    ['basics-course/start/Makefile', 1, 2, 0],
    ['basics-course/start/README.md', 1, 2, 3],
  ],
  repo30afterPull30: [
    ['.current.json', 1, 1, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/example/file3', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/example/subdir/file4', 1, 1, 1],
    ['basics-course/example/subdir/file5', 1, 1, 1],
    ['basics-course/start/Makefile', 0, 2, 0],
    ['basics-course/start/README.md', 1, 2, 1],
  ],
  repo30afterPull40: [
    ['.current.json', 1, 1, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/example/file3', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/example/subdir/file4', 1, 1, 1],
    ['basics-course/example/subdir/file5', 1, 1, 1],
    ['basics-course/start/Makefile', 0, 2, 0],
    ['basics-course/start/README.md', 1, 2, 1],
  ],
  repo30changedAllCommitted: [
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/example/file3', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/example/subdir/file4', 1, 1, 1],
    ['basics-course/example/subdir/file5', 1, 1, 1],
    ['basics-course/start/Makefile', 0, 2, 0],
    ['basics-course/start/README.md', 1, 2, 1],
  ],
  repo30afterPull50: [
    ['.current.json', 1, 1, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/anotherFile', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/example/file3', 1, 1, 1],
    ['basics-course/example/someFile', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/example/subdir/file4', 1, 1, 1],
    ['basics-course/example/subdir/file5', 1, 1, 1],
    ['basics-course/new/Makefile', 1, 1, 1],
    ['basics-course/new/README.md', 1, 1, 1],
    ['basics-course/start/Makefile', 0, 2, 0],
    ['basics-course/start/README.md', 1, 2, 1],
  ],
  repo30afterPull40Conflicts: [
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/file1', 1, 1, 1],
    ['basics-course/example/file3', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/example/subdir/file4', 1, 1, 1],
    ['basics-course/example/subdir/file5', 1, 1, 1],
    ['basics-course/start/Makefile', 0, 2, 0],
    ['basics-course/start/README.md', 1, 2, 1],
  ],
  repo30afterPull60: [
    ['.current.json', 1, 1, 1],
    ['.github/workflows/hexlet-check.yml', 1, 1, 1],
    ['README.md', 1, 1, 1],
    ['basics-course/example/.gitignore', 1, 1, 1],
    ['basics-course/example/Makefile', 1, 1, 1],
    ['basics-course/example/README.md', 1, 1, 1],
    ['basics-course/example/subdir/file2', 1, 1, 1],
    ['basics-course/start/Makefile', 1, 1, 1],
    ['basics-course/start/README.md', 1, 1, 1],
  ],
};
