module.exports = {
  repo10: [
    ['.gitignore', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
  repo20: [
    ['.gitignore', 1, 1, 1],
    ['exercises/example/file1', 1, 1, 1],
    ['exercises/start/Makefile', 1, 1, 1],
    ['exercises/start/README.md', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
  repo30: [
    ['.gitignore', 1, 1, 1],
    ['exercises/example/file1', 1, 1, 1],
    ['exercises/example/subdir/file2', 1, 1, 1],
    ['exercises/start/Makefile', 1, 1, 1],
    ['exercises/start/README.md', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
  repo30changed: [
    ['.gitignore', 1, 0, 1],
    ['exercises/example/file1', 1, 2, 1],
    ['exercises/example/file3', 0, 2, 0],
    ['exercises/example/file6', 0, 0, 3],
    ['exercises/example/subdir/file2', 1, 2, 2],
    ['exercises/example/subdir/file4', 0, 2, 2],
    ['exercises/example/subdir/file5', 0, 2, 3],
    ['exercises/start/Makefile', 1, 2, 0],
    ['exercises/start/README.md', 1, 2, 3],
    ['spec.yml', 1, 1, 0],
  ],
  repo30afterPull30: [
    ['exercises/example/file1', 1, 1, 1],
    ['exercises/example/file3', 1, 1, 1],
    ['exercises/example/subdir/file2', 1, 1, 1],
    ['exercises/example/subdir/file4', 1, 1, 1],
    ['exercises/example/subdir/file5', 1, 1, 1],
    ['exercises/start/Makefile', 1, 1, 1],
    ['exercises/start/README.md', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
  repo30afterPull40: [
    ['exercises/example/file1', 1, 1, 1],
    ['exercises/example/file3', 1, 1, 1],
    ['exercises/example/subdir/file2', 1, 1, 1],
    ['exercises/example/subdir/file4', 1, 1, 1],
    ['exercises/example/subdir/file5', 1, 1, 1],
    ['exercises/start/Makefile', 1, 1, 1],
    ['exercises/start/README.md', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
  repo30afterPull50: [
    ['exercises/example/anotherFile', 1, 1, 1],
    ['exercises/example/file1', 1, 1, 1],
    ['exercises/example/file3', 1, 1, 1],
    ['exercises/example/subdir/file2', 1, 1, 1],
    ['exercises/example/subdir/file4', 1, 1, 1],
    ['exercises/example/subdir/file5', 1, 1, 1],
    ['exercises/start/Makefile', 1, 1, 1],
    ['exercises/start/README.md', 1, 1, 1],
    ['exercises/start/TUTORIAL.md', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
  repo30afterPull60: [
    ['.gitignore', 1, 1, 1],
    ['exercises/example/subdir/file2', 1, 1, 1],
    ['exercises/start/Makefile', 1, 1, 1],
    ['exercises/start/README.md', 1, 1, 1],
    ['spec.yml', 1, 1, 1],
  ],
};
